### ISSUE TITLE
Icon support

### ISSUE THREAD

**Issue by joepio** [olback/tray-item-rs#1]
First off: thanks for putting effort into tackling this problem and sharing your solution. So, [`systray-rs`](https://github.com/qdot/systray-rs) was deprecated, because the developer didn't have time to catch up with all the rust changes. He basically warned others who wanted to make a successor to this to tackle the problem from a cross-platform perspective, which seems to be pretty hard to tackle. There's also [`trayicon-rs`](https://github.com/Ciantic/trayicon-rs/), but that does not have any cross-platform support at the time. So I'm really glad that you've actually created a very usable library for this exact purpose!

So onto the actual issue... I was wondering if you have any plans or ideas on icon support. How would that realistically function, cross-platform? 

Some considerations:

- On MacOS, tray icons are stencil-like, monochrome items. On Windows, tray icons are generally more detailed images. Supporting multiple (.png?) images would solve this

**Comment by olback** [comment]
I have merged #3 now which adds icon support to MacOS. So in theory, icons are now supported. I don't know how MacOS loads icons but both [Windows](https://docs.microsoft.com/en-us/windows/win32/menurc/about-resource-files) and [Linux](https://developer.gnome.org/gio/stable/GResource.html) can load them from a resource linked into the final output binary.

**Comment by joepio** [comment]
Thanks for adding this!

Not sure how to use it, though. The `set_icon` method accepts a string as an argument, but what should this string be? Looks like its a name of sorts. In other words, where do I put my actual icon? I'm kind of new to desktop apps, so maybe it's just general ignorance on my part.
