### ISSUE TITLE
MacOS: Unable to load icon

### ISSUE THREAD

**Issue by katopz** [olback/tray-item-rs#10]
```rust
    pub fn set_icon(&mut self, icon: &str) -> Result<(), TIError> {
        unsafe {
            let icon_name = NSString::alloc(nil).init_str(icon);
            self.icon = Some(NSImage::initWithContentsOfFile_(
                NSImage::alloc(nil),
                icon_name,
            ));
        }
        Ok(())
    }
```

I try to modify `set_icon` and use full path instead because I didn't know how `imageNamed_` consume icon there.
Anyway I didn't have much luck, even program didn't start properly when i changed.

Any hint is welcome.

**Comment by 0tabek16** [comment]
Found out that icon can be loaded using NSImage syntax, like `tray.set_icon('NSImageNameAddTemplate')`

But couldn't figure out a way to use custom PNGs 

@Absolucy can you help with that?

**Comment by Absolucy** [comment]
Could also probably add a new wrapper in tray-item that uses [`-[NSImage initWithContentsOfFile:]`](https://developer.apple.com/documentation/appkit/nsimage/1519918-initwithcontentsoffile?language=objc)

**Comment by 0tabek16** [comment]
Using `initWithContentsOfFile_()` with absolute path helped me :) Thanks

**Comment by AlexanderDKazakov** [comment]
By the way, is it possible to use the icon inside the binary?
For instance, I could use [rust_embeded](https://docs.rs/rust-embed/latest/rust_embed/index.html) in order to ship the binary with an icon, but so far I didn't find a way how I can extract that icon. Any suggestion would be great.

**Comment by LeeeSe** [comment]
Can you elaborate on this? I am also being confused by this issue

**Comment by oren0e** [comment]
@0tabek16 can you provide a full example of how you've managed to use this with `.set_icon()`?

**Comment by oren0e** [comment]
Thanks! looks good. I also wanted to disable the icon from the taskbar (=dock), but it seems this is only possible in Linux.

**Comment by 0tabek16** [comment]
@oren0e sorry for late response, AFAIK I used absolute path
```rs
    pub fn set_icon(&mut self, icon: &str) -> Result<(), TIError> {
        unsafe {
            let icon_name = NSString::alloc(nil).init_str(icon);
            self.icon = Some(NSImage::initWithContentsOfFile_(
                NSImage::alloc(nil),
                icon_name, // <- absolute path here
            ));
        }
        Ok(())
    }```

**Comment by katopz** [comment]
I didn't have time to try it yet but in case @0tabek16 confirm this has been solve so I will close it.
