### ISSUE TITLE
Windows quit can't call drop

### ISSUE THREAD

**Issue by nyrf** [olback/tray-item-rs#13]
```
std::process::exit(0);
```
quit app and it can't call https://github.com/olback/tray-item-rs/blob/404bdf67b28b5b5de42d42cda5bcca574a266cea/src/api/windows/mod.rs#L278, i've found this video https://www.youtube.com/watch?v=zQC8T71Y8e4

**Comment by olback** [comment]
What exactly is the issue?

**Comment by nyrf** [comment]
After quit app, the icon still appear and must move mouse to the icon, it would disappear. this is because of after quit, drop would't be called, so https://github.com/olback/tray-item-rs/blob/404bdf67b28b5b5de42d42cda5bcca574a266cea/src/api/windows/mod.rs#L249 and https://github.com/olback/tray-item-rs/blob/404bdf67b28b5b5de42d42cda5bcca574a266cea/src/api/windows/mod.rs#L262 would't be called.

**Comment by olback** [comment]
You don't have to use `std::process::exit()` at all. I'm using this in the example because it's just that, an example.

The proper way to handle things would be to have an event loop with messages. Something like the following:

```rust
enum Message {
    Quit
}

// Something like std::sync::mpsc::channel or crossbeam
let (tx, rx) = channel::<Message>();

tray.add_menu_item("Quit", move || {
    println!("Quit");
    tx.send(Message::Quit).unwrap();
})

loop {
    match rx.recv() {
        Ok(Message::Quit) => return
        _ => {}
    }
}

```

**Comment by nyrf** [comment]
Thanks for your help.
