### ISSUE TITLE
thread 'main' panicked at 'libappindicator3 library not found!'

### ISSUE THREAD

**Issue by dfurmans** [olback/tray-item-rs#18]
However the lib is on the place 

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
libappindicator3-1 is already the newest version (0.4.92-8).
```
OS :5.10.0-11-amd64 #1 SMP Debian 5.10.92-1

**Comment by dfurmans** [comment]
Debian is using libayatana-appindicator as the successor of libappindicator. For technical background see this [announcement.](https://lists.debian.org/debian-devel/2018/03/msg00506.html) 
ref: https://www.debian.org/releases/bullseye/amd64/release-notes/ch-information.en.html#noteworthy-obsolete-packages

**Comment by olback** [comment]
This issue comes from [libappindicator-rs](https://github.com/tauri-apps/libappindicator-rs). Working on a fix.

**Comment by olback** [comment]
Blocking PR: https://github.com/tauri-apps/libappindicator-rs/pull/28
