### ISSUE TITLE
Consider ksni crate for Linux

### ISSUE THREAD

**Issue by ancwrd1** [olback/tray-item-rs#2]
Instead of gtk and libappindicator consider using [ksni](https://github.com/iovxw/ksni) which implements dbus interfaces natively (libappindicator does it via C code anyway).
The advantage is much smaller dependency tree and the requirements for build environment.

**Comment by paulbricman** [comment]
+1, I've been having issues with libappindicator3 as well on Ubuntu. After `sudo apt-get install -y libappindicator3-1`, it still panicks with `libappindicator3 library not found!` on `cargo run --example linux`. Simpler requirements for the build environment would be great

**Comment by 31KM** [comment]
Please consider that not every DE/WM supports `org.kde.StatusNotifierItem` - see https://github.com/kondinskis/hyperx-cloud-flight/issues/12

**Comment by olback** [comment]
ksni is supported under a feature flag now.
