### ISSUE TITLE
System Tray Disappears On Windows When Explorer Crashes/Restarts

### ISSUE THREAD

**Issue by Ep0chalypse** [olback/tray-item-rs#25]
When explorer.exe crashes or restarts the icon disappears from the system tray. 

Steps to reproduce: 
* Run the windows example
* Open Task Manager to the Processes tab and find "Windows Explorer" and right click and then select "restart"

After a few seconds the taskbar will reload and when you navigate to the system tray area the icon will be gone but the application will still be running(you can see the process exe is still running if you look at Task Manager). No output is shown on the terminal you run the example from.

This seems to be due to windows wiping everything in the system tray when it crashes/restarts. I did some digging and it looks like windows provides a way to "listen" for when the system tray gets recreated so a app can readd itself. I just don't know enough to implement this and send a PR. 

This link provides some info on what happens https://docs.microsoft.com/en-us/windows/win32/shell/taskbar?redirectedfrom=MSDN#taskbar-creation-notification
> With Microsoft Internet Explorer 4.0 and later, the Shell notifies applications that the taskbar has been created. When the taskbar is created, it registers a message with the TaskbarCreated string and then broadcasts this message to all top-level windows. **When your taskbar application receives this message, it should assume that any taskbar icons it added have been removed and add them again.** This feature generally applies only to services that are already running when the Shell launches. The following example shows a very simplified method for handling this case.

> On Windows 10, the taskbar also broadcasts this message when the DPI of the primary display changes.

**Comment by sharunkumar** [comment]
I'm unable to build the windows example:

```
   Compiling windows v0.1.0 (D:\Code\Rust\tray-item-rs\examples\windows)
error[E0277]: `Sender<Message>` cannot be shared between threads safely
  --> src\main.rs:24:32
   |
24 |       tray.add_menu_item("Quit", move || {
   |            -------------         ^------
   |            |                     |
   |  __________|_____________________within this `[closure@src\main.rs:24:32: 24:39]`
   | |          |
   | |          required by a bound introduced by this call
25 | |         quit_tx.send(Message::Quit).unwrap();
26 | |     })
   | |_____^ `Sender<Message>` cannot be shared between threads safely
   |
   = help: within `[closure@src\main.rs:24:32: 24:39]`, the trait `Sync` is not implemented for `Sender<Message>`
note: required because it's used within this closure
  --> src\main.rs:24:32
   |
24 |     tray.add_menu_item("Quit", move || {
   |                                ^^^^^^^
note: required by a bound in `TrayItem::add_menu_item`
  --> D:\Code\Rust\tray-item-rs\src\lib.rs:43:26
   |
43 |         F: Fn() + Send + Sync + 'static,
   |                          ^^^^ required by this bound in `TrayItem::add_menu_item`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `windows` due to previous error
```

**Comment by dkrisman** [comment]
pull request open to fix this issue
https://github.com/olback/tray-item-rs/pull/45
