### ISSUE TITLE
How can I support other languages?

### ISSUE THREAD

**Issue by songlinshu** [olback/tray-item-rs#27]
![image](https://user-images.githubusercontent.com/45619496/200105690-41d31e36-ca11-436e-834a-f41f145ab933.png)

**Comment by fgimian** [comment]
I've been going through the code today and there was a rather large bug when setting the tooltip which you've discovered.

I've done a major refactor of the Windows implementation and also switched to windows-rs.  I've verified my version works correctly with Unicode.  Give it a try at https://github.com/fgimian/tray-item-rs/tree/switch-to-windows-rs 😄

**Comment by songlinshu** [comment]
Thank you!

**Comment by fgimian** [comment]
Hey there @songlinshu, I suggest switching to https://github.com/tauri-apps/tray-icon for this functionality. I'll be deleting my fork of this repository in 1 week. Just thought I'd let you know in case you wanted to grab a copy. 😄

**Comment by olback** [comment]
This should be fixed now that we're using windows-rs instead of winapi.
